apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: htpass-secret
  namespace: openshift-config
spec:
  encryptedData:
    htpasswd: AgC8KFv0eApqcofVBd8x5uMNR2k26TdZ/6nWkWGEFEtXun0bf92c+FC4iqfn/remBPKzuMq0Hck2Tq9B3Qqkwj+jZOg8ajVut3zV2MhWHLsBDGcP31HmgyVpiW7B0d1CUoqLZMoVbmJCgV1BsM6hjIkP6n+OBUNIUPokF6yVUCJCRJPU3ovhnh8hNL0r4oD/dsyzmO9coHrnIiNudVHh5J73vw0pJFWHTLviOHM3k+LaflunnfMGqOy1Ff5ZORatDvjndyBOnKbvl0Fn3rQ+A5VoETXnAbEJqrh90gvr1MNoQF9OMzH5cu2yAPoxxyR4zDxZ8m2hpMrQLkQnWgJVECi0sxoRoNVxtAjgMJQTWdF1HYsBVUBLxk2uoW9KGE4tjo5NPo7BbVRTMSPjDdZgiJc3vEe+w05/h0Z9HEiU/ifiIaZ4mZ0gVaOfGxddaBhhy3LNv7kHrj+CqwuCyqO6AMyeE2P57jkz3CXn0TLAU/EJZBherSFuJwBwDtiVo7hF3OVYekp8h785wVEL2MAmenoBDjJTXXoFbRo45VdnevODpoIi7imazW4vmJ6WhQiLGIbwYF8cMkOqZEIaT37zAfxSkHNz+QkB2Zso7dfV62NdIH7cIOuZwt0PZdwI12exejwCmlZoCjWQHm4mRSsdAEm2SK2a2psdrwjrIJmiA5xDSDKtzOK84m+q5ys0TWbiIf+71RXfLm6HzgcnUePBBmpHU7DhuA2HPD9zfupLea74EqP1ox3GZQ6bPkDurmWi+uQuQuW4sRQtQMu4yYvT4rUS/UwICxDkrWwQzphPawtpUO+CdskDVE21q6KD/JUxbvRKg17I3PdKdGpQqArQ+lhnjBJKA4Gre5uqq7GmRxUxZMRV4VoV4gHMuj9640JHrYmkylzQWP9HmqD3xUWfgOFkwLppr41v0POQOqRu2gE+zWfGiaxxdylox636IiQPE6qRqLAruKiF3PAyjG6tN/x0w0qJYfkehRWyQFu4Xf/NEsYs7Nc+jbo19Nd4gpgd1Skf97+1rQAy+9XJccZgHIRTEB+j1QTRt2227f9KV7/O1f2FSZvdTNc077cdQiwuqa80b1o0cSWrjR/OZl3inmFMi9gwi597rRnKbspY2M0w8764TaC/wiO39KztYtn7LQWf1F6rtr2n8hK9/RanzODINHtxJ+7ndlIWXjnWN8GAUlX6g6XsHu5u4mvlbs7g6UeNOoYejH/eMjGEBE2bgLvgt/85Uv8OsksBfbsKNDOp6gqZhZUgj0is0IQpInM2HbGELeLfIUC9xdJfy1E0F0eg56t84hBSaLuDcuEAgAw2B6cowgPhMakyrESn6+WXkddM2IB+HlzxRXBPSDJhqzulmfRkWMnr8eASzL6qYAP8KG9RUOGXw42ezlJbPejuAm+CR9UOiwe0M6SBHxG6w+AmBlo9Amrlvyv9z1GIIegT/u/7DJ39ueARDWWcNMAy6DX7O48jEdZ/ixIvRdKUO9wu1Jrkw2bMFARQdRTFvF+Ji/5R3ZYkMJl4wjbD1L7noXMqmq9NvR/0OK1iQ3HUu38cFFhZ1bx7BHpGaDc6kEW64onaT+LGslQ9NFvkTxWIKy+smcT4vJ3hTWR8dY7NyCIR3QJrjvjrT9kY0mvNcku5KvPHMnDn3A==
  template:
    metadata:
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
        argocd.argoproj.io/sync-options: Prune=false
      creationTimestamp: null
      name: htpass-secret
      namespace: openshift-config
    type: Opaque
