apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: htpass-secret
  namespace: openshift-config
spec:
  encryptedData:
    htpasswd: AgAnGk3VNEPFnvauxnzQ2GooQ5CuVQ7xvWD5sFCMqvNCP3NWFPdQUzNK5BeQMYOHCtPM4nqOS7JtJvCaC6bDFXA0y5R3U8Kl3CxoONmgXJDisvO8EwOLvezEwkOH5ehetvjvtHSNJczLpXT6f4zb1roitKhbO3/tYA1u7UZqVw4SOjjl0AJf/Y+KcD2A+MjbDX3k/hHl4Dv6Sx6WjlepL9VNSFdxYGXpOxeYnOGlb5r+HUdAwxdCJ9s1VF6NXuIIJ+9dlgSX0KxIuY/Avitm47U6GGXGFaE1KP1OiEnqpH+keQcC4IvkIN4WOXjHjAq+3oOrEQTQRiXwOC3e2/jxGDGyajBOzTvLIPpnGPEtiIf7t9djux5PLbAYJziRBmrvAEL5HyxnJFG1sVaFSOpXO2Wo6i3kRlUiPRvn+cYt88AJ4E4vJLZokMrNK3o/4Q9wBVx/IYYPl+6Lttnlvyb0ntAXgHN+V5oDgyc6AwfgupK9z7i3KX94o8oi2w7SqFRdB2/TNT/8h/gRzzQSfVZhWsHMluR6vdnJO6qaHUtq9jiBDq/Xndd6J505oUgXj0ifqz9/iUfCg06yJACAMmAFzEM7TMkp8uKf67fjN8AhrCr7WZyH/5e18X3Qrpz83vNnofPsTz8s9CORQLdrpSSxCVnon9lWkv53j/dJssSBS0iibLc24+hIyrpQmIYA9duCty1IxUTFKepFQZD1IIloXsO6bLbAABbVaWAVcLhaEVm77IgUbfuzEQmy48sp+7XAprOZKulCpiQCHOfWm7ddL6NjVZ8FHHeRWVnfk/dARhNwZ8Z23Xr6zT9tohhLmk0+JeeyED8973WVNkxWwqwMPvC/KS1GFA6VEYerBCPFC5GQVPxtfV/L4k3gBQc/8mMrJ2DUPsQevj5yZuVrWbtvcwMUuJuAEtpsLgGaeikVzrj7NYno9xiWUmSDUgDmb7q7scBFQ1W3Hq9dazu1PKyKbAnNv20xpFF2OsiGO4UwV7klp4FBBAh0i+uDNvQ6ait2dj+u5AiXSMItfASk13A40P3Iahvthj3sd7UD58wXJWUqGoyQItjaTdi0YxoCP7aK2HU3l2VIInvMlyHgK6wukS7eNNLLzn3hpen9adzgrtu0aXqWwhYVSp5rlWItbBVhbGbgBfni+M4vK+hdxDQfE99z2cArfqruYVNaTc3r5CTwyddNwpwxm9ZPcvbu6G+2UIOafy67CSXbXrKrZBVswyf7gwApPCLukUfGpReXHUx1xGNTAtNv+HN5Pg0kgoPnNv2PZqIOnmbSJ16cFctxswqUgkD2QRDj51PyoDy5ZC3+vmjAlw1rnb37fTPV9naJ/EOQ7yPOcqFY70GtkQ5CMEQP3W0ADdT2d3OUznHWEm6C//5xICjUFQE3NW86RfwrQVN/ds/haRdZ3e9KMT2SVzNDknr6HvteDuxC1IAmBDUwGU0BEikCLAlNWLBRWV1zjOM24fYtjtDlW6CzilJ/d53Fmw+aVD1hEBoeFgTJSBBdtRbtp/nJFO8mkkITrKP4q/Bw8TqwlcqLtpbzeKbVs3EY17i5mTLwdpYI3ncoKurZsLoUObXX8+6CwiWWFJsmltsAkbIeAIgpZC66GpqoYJFCq8sP9NbgUK8NPVc1
  template:
    metadata:
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
        argocd.argoproj.io/sync-options: Prune=false
      creationTimestamp: null
      name: htpass-secret
      namespace: openshift-config
    type: Opaque
