apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- htpass-auth.yaml
- rbac.yaml
- container-security-operator.yaml
- nodejs-frontend.yaml
- nodejs-db.yaml
- nodejs-namespace.yaml
